---
name: Bug Report
about: Something's not working right
title: '[BUG] '
labels: ['bug']
assignees: ''
---

## What happened?
Describe what went wrong.

## How to reproduce it
1. Run this command: `...`
2. With this input: `...`
3. Got this error: `...`

## What did you expect?
What should have happened instead?

## Your setup
- OS: [e.g., Ubuntu 20.04, macOS 12.0, Windows 10]
- Python version: [e.g., 3.9.0]
- RAI Toolkit version: [e.g., 1.0.0]
- Installation method: [e.g., pip, Docker, from source]

## 📊 Tool/Component
Which RAI Toolkit component is affected?
- [ ] PII Scanner
- [ ] Toxicity Evaluator  
- [ ] Bias Auditor
- [ ] Evaluation Runner
- [ ] Templates
- [ ] Policies
- [ ] CI/CD Integration
- [ ] Documentation
- [ ] Other: ___________

## 📎 Additional Context
- Error messages or logs
- Screenshots (if applicable)
- Related issues or PRs