---
name: Feature Request
about: Suggest something new
title: '[FEATURE] '
labels: ['enhancement']
assignees: ''
---

## What would you like to see?
Describe the feature or improvement.

## Why do you need this?
What problem would this solve for you?

## Your situation
- What's your role? [e.g., Data Scientist, Compliance Officer, Developer]
- What kind of organization? [e.g., Startup, Enterprise, Research]  
- How do you handle this today?

## 📋 Detailed Requirements
What should this feature do?
- [ ] Requirement 1
- [ ] Requirement 2
- [ ] Requirement 3

## 🎨 Proposed Solution
If you have ideas on how to implement this:

## 🔗 Integration Points
How should this integrate with existing RAI Toolkit components?
- [ ] Evaluation tools
- [ ] Templates
- [ ] CI/CD workflows
- [ ] Governance policies
- [ ] Documentation
- [ ] Other: ___________

## 📊 Success Criteria
How will we know this feature is successful?

## 🚀 Priority/Impact
- **Priority:** [High/Medium/Low]
- **Impact on RAI practices:** [High/Medium/Low]
- **Implementation complexity:** [High/Medium/Low]

## 📎 Additional Context
- Similar tools or examples
- References to standards or regulations
- Links to relevant documentation